version: 2.0
jobs:
 build:
   machine:
     image: circleci/classic:latest
   steps:
     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'
